DEBUG     := n
TARGET    := espioob
OBJS      := espioobmain.o

EXTRA_CFLAGS += -I${SPXINC}/global
EXTRA_CFLAGS += -I${SPXINC}/dbgout
EXTRA_CFLAGS += -I${SPXINC}/helper
EXTRA_CFLAGS += -I${SPXINC}/espi

-include ${TOOLDIR}/rules/Rules.make.drivers

